// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyADBjbMbCZdRlw-8QatmhYsR4tker51SG8',
    appId: '1:727501484786:web:8895ab4dd6217febf7166b',
    messagingSenderId: '727501484786',
    projectId: 'notesappflutter-c6c78',
    authDomain: 'notesappflutter-c6c78.firebaseapp.com',
    storageBucket: 'notesappflutter-c6c78.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAu22V1T_zccFXaMnmxvpIJdZOyEUvNllA',
    appId: '1:727501484786:android:dc2e39b7d2313123f7166b',
    messagingSenderId: '727501484786',
    projectId: 'notesappflutter-c6c78',
    storageBucket: 'notesappflutter-c6c78.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCx0qQoUbftS6B0HVrtAmPquByYFshXyLw',
    appId: '1:727501484786:ios:f88f520ff2ecbe76f7166b',
    messagingSenderId: '727501484786',
    projectId: 'notesappflutter-c6c78',
    storageBucket: 'notesappflutter-c6c78.appspot.com',
    iosClientId: '727501484786-sagitfpkm9o9khk6gu7j3dh79b7i65iv.apps.googleusercontent.com',
    iosBundleId: 'com.example.notesApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCx0qQoUbftS6B0HVrtAmPquByYFshXyLw',
    appId: '1:727501484786:ios:f88f520ff2ecbe76f7166b',
    messagingSenderId: '727501484786',
    projectId: 'notesappflutter-c6c78',
    storageBucket: 'notesappflutter-c6c78.appspot.com',
    iosClientId: '727501484786-sagitfpkm9o9khk6gu7j3dh79b7i65iv.apps.googleusercontent.com',
    iosBundleId: 'com.example.notesApp',
  );
}
